/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RqVDtma6FR9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { format, parse } from "date-fns";
import { useState } from "react";
import { PlannedNap } from "@/domain/ChildDay";

type Props = {
  children: React.ReactNode;
  onNapUpdated: (data: { startDate: Date; endDate: Date }) => void;
  nap: PlannedNap;
};

const napTimeSchema = z.object({
  startTime: z.string(),
  endTime: z.string(),
});

type NapTimeSchema = z.infer<typeof napTimeSchema>;

export const UpdateNapDrawer = ({ children, onNapUpdated, nap }: Props) => {
  const [open, setOpen] = useState(false);
  const form = useForm<NapTimeSchema>({
    resolver: zodResolver(napTimeSchema),
    defaultValues: {
      startTime: format(nap.startDate, "HH:mm"),
      endTime: format(nap.endDate, "HH:mm"),
    },
  });

  const onSubmit = (e: NapTimeSchema) => {
    const startDate = parse(e.startTime, "HH:mm", new Date());
    const endDate = parse(e.endTime, "HH:mm", new Date());
    onNapUpdated({ startDate, endDate });
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-[420px]">
        <DialogHeader>
          <DialogTitle>Update Nap Times</DialogTitle>
          <DialogDescription>
            Select new start and end times for the nap.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <div className="grid gap-6 py-6">
              <FormField
                control={form.control}
                name="startTime"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel htmlFor="newTime">New Start Time</FormLabel>
                    <FormControl>
                      <Input
                        type="time"
                        className="flex items-center justify-between w-full"
                        {...field}
                      ></Input>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              ></FormField>
              <FormField
                control={form.control}
                name="endTime"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel htmlFor="newTime">New End Time</FormLabel>
                    <FormControl>
                      <Input
                        type="time"
                        className="flex items-center justify-between w-full"
                        {...field}
                      ></Input>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              ></FormField>
            </div>
            <DialogFooter className="flex flex-col-reverse gap-4 sm:flex-row sm:items-center sm:justify-between">
              <Button variant="outline" className="w-full sm:w-auto">
                Cancel
              </Button>
              <Button type="submit" className="w-full sm:w-auto">
                Save
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};
